[package]
name = "merkle-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
rs_merkle = "1.4"
tiny-keccak = { version = "2.0", features = ["keccak"] }
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"